export default {
  SPLASHSCREEN: "SplashScreen",
  LOGINSCREEN: "LoginScreen",
  DELIVEYBOTTOMTAB: "DeliveyBottomTab",
  ADMINBOTTOMTAB: "AdminBottomTab",
  ADMINORDERDETAILS: "AdminOrderDetails",
  ADMINMYCREDITS: "AdminMyCredits",
  ADMINAPPROVECREDIT: "AdminApproveCredit",
  ADMINPAYMENT: "AdminPayment",
  ADMINMYCUSTOMER: "AdminMyCustomer",
  ADMINMYCUSTOMERDETAILS: "AdminMyCustomerCustomerDetails",
  ADMINMYCUSTOMERORDERDETAILS: "AdminMyCustomerCustomerOrderDetails",
  ADMINCOLLECTPAYMENT: "AdminCollectPayment",
  DELIVERYHOMESCREEN: "DeliveryHomeScreen",
  DELIVERYPROFILESCREEN: "DeliveryProfileScreen",
  DELIVERYTRANSACTIONHISTORYSCREEN: "DeliveryTransactionHistoryScreen",
  DELIVERYAPPROVECREDITYSCREEN: "DeliveryApproveCreditScreen",
  DELIVER: "Deliver",
  ADMINHOMESCREEN: "AdminHomeScreen",
  ADMINTRANSACTIONSCREEN: "AdminTransactionHistory",
  ADMINPROFILESCREEN: "AdminProfileScreen",
  PERMISSIONSCREEN: "PermissionScreen",
  SCANQRCODESCREEN: "QrCodeScanScreen",
  ASSIGNORDER: "AssignOrder",
  DELIVERADMIN: "DeliverAdmin",
};
